package org.neo4j.geoff;

public enum RelState {

	DEFINED_AND_CORRECTLY_TYPED,
	DEFINED_AND_INCORRECTLY_TYPED,
	DEFINED_AND_UNTYPED,
	UNDEFINED_AND_TYPED,
	UNDEFINED_AND_UNTYPED,
	MISSING_AND_TYPED,
	MISSING_AND_UNTYPED

}
